name: Code Quality Accessment

on:
  pull_request:
    branches: [main, experimental]
  push :
    branches: [main, experimental]


jobs:
  Code_Accessment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - name: Install Dependencies
        run: npm install
      - name: Lint Code
        run: npm run lint
      - name: Run Tests
        run: npm run test

